version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: yourdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/neurodb.sql:/docker-entrypoint-initdb.d/init.sql
